config/routes.rb
Rails.application.routes.draw do
  resources :email_magazines

  resources :recipes, only: [:new, :create, :edit, :show, :update] do
    get :search, on: :collection
    member do
      delete :delete_image
      patch :publish
    end

    resources :directions, only: [:create, :update, :destroy] do
      member do
        delete :delete_image
        patch :move_highter
        patch :move_lower
      end
    end

    resources :tukurepos, only: [:create]
  end

  resources :kitchens, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  after_destroy :reorder_steps

  belongs_to :recipe

  has_attached_file :image, styles: { medium: "136x214>" },
    storage: :s3,
    s3_permissions: :private,
    s3_credentials: "#{Rails.root}/config/s3.yml",
    path: ":class/:id/:style_:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def save_and_reorder
    Direction.transaction do
      Direction.where('recipe_id = ? and step >= ?', self.recipe_id, self.step).
        update_all('step = step + 1')
      self.save
    end
  end

  def move(type)
    if type == :higher
      if self.step == 1
        errors.add(:step, "はすでに先頭です")
        return false;
      end
      val = -1
    else
      max_step = Direction.where("recipe_id = ?", self.recipe_id).maximum(:step)
      if max_step == self.step
        errors.add(:step, "はすでに最後です")
        return false;
      end
      val = 1
    end
    self.step += val
    direction = Direction.find_by(recipe_id: self.recipe_id, step: self.step)
    direction.step -= val

    Direction.transaction do
      self.save
      direction.save
    end
    return true
  end

  def authenticated_image_url(style)
    if image.present?
      image.s3_object(style).url_for(:read, secure: true)
    else
      image.url(style)
    end
  end

  private

  def reorder_steps
    Direction.where('recipe_id = ? and step > ?', self.recipe_id, self.step).update_all('step = step - 1')
  end
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe
  before_action :set_direction, only: [:update, :destroy, :delete_image, :move_highter, :move_lower]

  def create
    direction = @recipe.directions.build(direction_params)
    direction.save_and_reorder
    render :directions
  end

  def update
    @direction.update!(direction_params)
    respond_to do |format|
      format.html { redirect_to edit_recipe_path(@direction.recipe_id) }
      format.js { render :directions }
    end
  end

  def destroy
    @direction.destroy!
    render :directions
  end

  def delete_image
    @direction.image = nil
    @direction.save
    render :directions
  end

  def move_highter
    @direction.move(:higher)
    render :directions
  end

  def move_lower
    @direction.move(:lower)
    render :directions
  end

  private

  def direction_params
    params.require(:direction).permit(:image, :description, :step)
  end

  def set_recipe
    @recipe = current_user.recipes.find(params[:recipe_id])
  end

  def set_direction
    @direction = @recipe.directions.find(params[:id])
  end
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/views/directions/_direction_image_form.html.haml
.direction_image_form
  .direction_image_upload(data-direction_id="#{direction.id}")
    - if direction.image?
      = image_tag direction.authenticated_image_url(:medium)
    - else
      %div 写真をのせる
  = link_to '写真を削除', delete_image_recipe_direction_path(direction.recipe_id, direction.id), method: :delete, data: { confirm: '削除した写真は元に戻すことができません。本当に削除しますか？' }, remote: true if direction.image?
  .hide
    = form_for direction, url: recipe_direction_path(direction.recipe_id, direction.id), method: :patch, html: { multipart: true } do |f|
      = f.file_field :image, id: "direction_image_#{direction.id}"
      = f.submit '保存'

app/views/directions/_direction_text_form.html.haml
%p.direction_text(data-direction_id="#{direction.id}")= br(direction.description) || 'クリックして作り方を入力'
.direction_text_form
  = form_for direction, url: recipe_direction_path(direction.recipe_id, direction.id), method: :patch, remote: true do |f|
    = f.text_area :description, rows: 3, id: "direction_text_#{direction.id}"
    .actions
      = f.submit '保存'
      = link_to '取消', "javascript:void(0)", { class: 'edit_direction_text_cancel' }

app/views/directions/_directions.html.haml
- directions.sort_by{|d| d.step}.each do |direction|
  .hbox_list
    %dl
      %dt
        %h4
          = direction.step
          %span= link_to '←', move_highter_recipe_direction_path(direction.recipe_id, direction.id), method: :patch, remote: true
          %span= link_to '→', move_lower_recipe_direction_path(direction.recipe_id, direction.id), method: :patch, remote: true
        = link_to '削除', recipe_direction_path(direction.recipe_id, direction.id), method: :delete, data: { confirm: 'この作り方を削除しますか？' }, remote: true if direction.id
        = link_to '追加', recipe_directions_path(direction.recipe_id, direction: { step: direction.step + 1}), method: :post, remote: true
      %dd
        = render 'directions/direction_image_form', direction: direction
        = render 'directions/direction_text_form', direction: direction

app/views/directions/directions.js.erb
$("#directions").html("<%= j render 'directions', directions: @recipe.directions %>");