config/routes.rb
Rails.application.routes.draw do
  resources :email_magazines

  resources :recipes, only: [:new, :create, :edit, :show, :update] do
    get :search, on: :collection
    member do
      delete :delete_image
      patch :publish
    end

    resources :directions, only: [:create, :update, :destroy] do
      member do
        delete :delete_image
        patch :move_highter
        patch :move_lower
      end
    end

    resources :tukurepos, only: [:create]
  end

  resources :kitchens, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  extend Enumerize
  enumerize :status, in: { draft: 'draft', published: 'published' }, default: :draft

  belongs_to :user
  has_many :ingredients
  has_many :directions
  has_many :tukurepos

  accepts_nested_attributes_for :ingredients, allow_destroy: true,
    reject_if: proc { |attributes| attributes['title'].blank? }
  accepts_nested_attributes_for :directions, allow_destroy: true,
    reject_if: proc { |attributes| attributes['description'].blank? }
  accepts_nested_attributes_for :tukurepos, allow_destroy: true,
    reject_if: proc { |attributes| attributes['message'].blank? }

  has_attached_file :image, styles: { medium: "280x420>", thumb: "140x210>" },
    default_url: "no-image.png", storage: :s3, s3_permissions: :private,
    s3_credentials: "#{Rails.root}/config/s3.yml", path: ":class/:id/:style_:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  scope :published, -> { where(status: :published) }
  scope :keywords_search, ->(keywords) {
    tokens = keywords.split(/[[:space:]]/).delete_if(&:empty?).map { |token| "%#{token}%" }
    if tokens.present?
      recipes = where{ (title.matches_any tokens) | (catch_copy.matches_any tokens) }
    end
  }

  def build_child_items
    if self.ingredients.empty?
      3.times { self.ingredients.build }
    end

    if self.directions.empty?
      (1..4).each { |i| self.directions.create(step: i) }
    end
  end

  def publish
    self.status = :published
    self.save
  end

  def authenticated_image_url(style)
    if image.present?
      image.s3_object(style).url_for(:read, secure: true)
    else
      image.url(style)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search]
  before_action :set_recipe, only: [:edit, :update, :delete_image, :publish]

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to edit_recipe_path(@recipe) }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @recipe.build_child_items
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to edit_recipe_path(@recipe) }
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def delete_image
    @recipe.image = nil
    @recipe.save
    redirect_to edit_recipe_path(@recipe)
  end

  def show
    @recipe = Recipe.published.find(params[:id])
  end

  def publish
    if @recipe.publish
      redirect_to @recipe, notice: '公開しました'
    else
      render :edit
    end
  end

  def search
    @keywords = params[:search].squish.presence || 'すべて'
    @recipes = Recipe.keywords_search(params[:search]).published.page(params[:page]).per(3)
  end

  private

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:image, :title, :catch_copy,
      ingredients_attributes: [:id, :title, :quantity, :_destroy],
      directions_attributes: [:id, :step, :image, :description, :_destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def ingredients_title_example(index)
    case index
    when 0 then '例）豚肉'
    when 1 then '例）にんじん'
    when 2 then '例）大根'
    else nil
    end
  end

  def ingredients_quantity_example(index)
    case index
    when 0 then '例）350g'
    when 1 then '例）1本'
    when 2 then '例）1/2本'
    else nil
    end
  end
end

app/views/recipes/_catch_copy.html.haml
%p#catch_copy_text= br(recipe.catch_copy) || 'クリックしてキャッチコピーを入力'
#catch_copy_form
  = form_for recipe, remote: true do |f|
    = f.text_area :catch_copy, rows: 3, placeholder: 'このレシピのキャッチコピーを入力（検索結果にも表示されます）'
    .actions
      = f.submit '保存'
      = link_to '取消', "javascript:void(0)", { id: 'cancel_catch_copy_form' }

app/views/recipes/_errors.html.haml
- if @recipe.errors.any?
  #error_explanation.alert-warning
    %h4= pluralize(@recipe.errors.count, "error")
    - @recipe.errors.full_messages.each do |msg|
      %p= msg

app/views/recipes/_form_tukurepo.html.haml
= form_for @recipe.tukurepos.build, url: recipe_tukurepos_path(@recipe), html: { multipart: true} do |f|
  = token_tag
  .form-group
    = f.file_field :image
    %span(class="help-block")
  .form-group
    = f.text_area :message, rows: 3, placeholder: 'メッセージを入力してください', class: 'form-control'
    %span(class="help-block")
  .actions
    = f.submit '送信する', class: 'btn btn-default'

app/views/recipes/_ingredient_dialog.html.haml
#edit_direction_modal.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h4#myModalLabel.modal-title 材料
      .modal-body
        = nested_form_for @recipe, html: { multipart: true } do |f|
          = f.fields_for :ingredients do |ff|
            .field
              - i = ff.options[:child_index]
              = ff.text_field :title, placeholder: ingredients_title_example(i)
              = ff.text_field :quantity, placeholder: ingredients_quantity_example(i)
              = ff.link_to_remove "削除"
          %p= f.link_to_add "行を追加する", :ingredients
          .panel.panel-default
            .panel-body
              %p.text-warning 分かりやすい分量で、みんながおいしく作れるレシピに！
              %p.text-warning 例：適量 → 小さじ1
          = f.submit '保存して閉じる'
      .modal-footer
        %button.btn.btn-default(type="button" data-dismiss="modal") Close

app/views/recipes/_ingredients_form.html.haml
#ingredients_form.modal.fade(tabindex="-1" role="dialog" aria-labelledby="ingredients_form" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h4.modal-title 材料
      .modal-body
        = nested_form_for recipe do |f|
          = f.fields_for :ingredients do |ff|
            .field
              - i = ff.options[:child_index]
              = ff.text_field :title, placeholder: ingredients_title_example(i)
              = ff.text_field :quantity, placeholder: ingredients_quantity_example(i)
              = ff.link_to_remove "削除"
          %p= f.link_to_add "行を追加する", :ingredients
          .panel.panel-default
            .panel-body
              %p.text-warning 分かりやすい分量で、みんながおいしく作れるレシピに！
              %p.text-warning 例：適量 → 小さじ1
          = f.submit '保存して閉じる'
      .modal-footer
        %button.btn.btn-default(type="button" data-dismiss="modal") Close

app/views/recipes/_recipe_image.html.haml
= link_to '画像を削除', delete_image_recipe_path, method: :delete, data: { confirm: '削除した写真は元に戻すことができません。本当に削除しますか？' } if @recipe.image?
.hide
  = form_for recipe do |f|
    = f.file_field :image
    = f.submit '保存'
= image_tag recipe.authenticated_image_url(:medium), id: 'recipe_image_upload'

app/views/recipes/_recipe_title.html.haml
%h1#recipe_title_text.text-success= recipe.title
#recipe_title_form
  = form_for recipe, remote: true do |f|
    = f.text_field :title, size: 60
    = f.submit '保存'
    = link_to '取消', "javascript:void(0)", { id: 'cancel_recipe_title_form' }

app/views/recipes/edit.html.haml
.container
  .row
    .col-12
      =render 'errors'
  .row
    .col-md-8
      #recipe_title_wrapper
        = render 'recipe_title', recipe: @recipe
  .row
    .col-md-3
      = render 'recipe_image', recipe: @recipe
    .col-md-5
      #catch_copy_wrapper
        = render 'catch_copy', recipe: @recipe
      #ingredients
        %h4 材料
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li
              %span= ingredient.title
              %span.badge= ingredient.quantity
  .row
    .col-md-8
      %h4 作り方
      #directions
        = render 'directions/directions', directions: @recipe.directions
  .row
    .col-md-8
      %p= link_to 'レシピを公開', publish_recipe_path, method: :patch, class: "btn btn-primary", data: { confirm: 'レシピを公開します。よろしいですか？'}

= render 'ingredients_form', recipe: @recipe

app/views/recipes/new.html.haml
.container
  .row
    .col-md-8
      %h1 レシピをのせる

      = form_for @recipe do |f|
        = render 'errors'
        .field
          = f.label :title, 'レシピのタイトル（※あとから変更できます）'
          = f.text_field :title, size: 80
        %p #{link_to '掲載するレシピのガイドライン'} を読んで理解しました
        .actions
          = f.submit '材料・作り方の入力に進む'

app/views/recipes/search.html.haml
.container
  .row
    .col-md-8
      %h2 「#{@keywords}」のレシピ

  - @recipes.each do |recipe|
    .row
      .col-md-2
        = link_to image_tag(recipe.authenticated_image_url(:thumb), size: "105x168"), recipe
      .col-md-6
        %h4= link_to recipe.title, recipe
        %p= recipe.catch_copy
    %br

  = paginate @recipes, params: { contoller: 'recipe', action: 'search' }

app/views/recipes/show.html.haml
.container
  .row
    .col-12
      = render 'errors'

  .row
    .col-md-8
      %h1.text-success= @recipe.title

  .row
    .col-md-3
      = image_tag @recipe.authenticated_image_url(:medium)

    .col-md-5
      = @recipe.catch_copy

      %h4 材料
      %ul.list-group
      - @recipe.ingredients.each do |ingredient|
        %li.list-group-item
          %span= ingredient.title
          %span.badge= ingredient.quantity

  .row
    .col-md-8
      %h4 作り方
      - @recipe.directions.sort_by{|d| d.step}.each do |direction|
        .hbox_list
          %dl
            %dt
              %h4= direction.step
            %dd
              %div= image_tag direction.authenticated_image_url(:medium) if direction.image?
              %p= direction.description

  .row
    .col-md-8
      %h4 みんなのつくりましたフォトレポート「つくれぽ」（#{@recipe.tukurepos.count}件）
      - @recipe.tukurepos.last(4).each do |tukurepo|
        = render tukurepo

  .row
    .col-md-8
      %p.text-center= link_to "もっと見る（#{@recipe.tukurepos.count}件）" if @recipe.tukurepos.count > 4

  .row
    .col-md-8
      %p.text-center= link_to 'つくれぽを送る', '#new_tukurepo_modal', 'data-toggle' => 'modal', class: 'btn btn-primary'

#new_tukurepo_modal.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h4#myModalLabel.modal-title #{@recipe.title} へのつくれぽ
      .modal-body
        = render 'tukurepos/tukurepo_form'
      .modal-footer
        %button.btn.btn-default(type="button" data-dismiss="modal") Close

app/views/recipes/update.js.erb
$("#recipe_title_wrapper").html("<%= j render 'recipe_title', recipe: @recipe %>");
$("#catch_copy_wrapper").html("<%= j render 'catch_copy', recipe: @recipe %>");