config/routes.rb
Rails.application.routes.draw do
  resources :email_magazines

  resources :recipes, only: [:new, :create, :edit, :show, :update] do
    get :search, on: :collection
    member do
      delete :delete_image
      patch :publish
    end

    resources :directions, only: [:create, :update, :destroy] do
      member do
        delete :delete_image
        patch :move_highter
        patch :move_lower
      end
    end

    resources :tukurepos, only: [:create]
  end

  resources :kitchens, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
end

app/models/email_magazine.rb
class EmailMagazine < ActiveRecord::Base
  has_many :users, through: :subscriptions
  has_many :subscriptions
end

app/controllers/email_magazines_controller.rb
class EmailMagazinesController < ApplicationController
  before_action :set_email_magazine, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @email_magazines = EmailMagazine.all
    respond_with(@email_magazines)
  end

  def show
    respond_with(@email_magazine)
  end

  def new
    @email_magazine = EmailMagazine.new
    respond_with(@email_magazine)
  end

  def edit
  end

  def create
    @email_magazine = EmailMagazine.new(email_magazine_params)
    @email_magazine.save
    respond_with(@email_magazine)
  end

  def update
    @email_magazine.update(email_magazine_params)
    respond_with(@email_magazine)
  end

  def destroy
    @email_magazine.destroy
    respond_with(@email_magazine)
  end

  private
    def set_email_magazine
      @email_magazine = EmailMagazine.find(params[:id])
    end

    def email_magazine_params
      params.require(:email_magazine).permit(:title)
    end
end

app/helpers/email_magazines_helper.rb
module EmailMagazinesHelper
end

app/views/email_magazines/_form.html.haml
= form_for @email_magazine do |f|
  - if @email_magazine.errors.any?
    #error_explanation
      %h2= "#{pluralize(@email_magazine.errors.count, "error")} prohibited this email_magazine from being saved:"
      %ul
        - @email_magazine.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/email_magazines/edit.html.haml
%h1 Editing email_magazine

= render 'form'

= link_to 'Show', @email_magazine
\|
= link_to 'Back', email_magazines_path

app/views/email_magazines/index.html.haml
%h1 Listing email_magazines

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @email_magazines.each do |email_magazine|
    %tr
      %td= email_magazine.title
      %td= link_to 'Show', email_magazine
      %td= link_to 'Edit', edit_email_magazine_path(email_magazine)
      %td= link_to 'Destroy', email_magazine, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Email magazine', new_email_magazine_path

app/views/email_magazines/new.html.haml
%h1 New email_magazine

= render 'form'

= link_to 'Back', email_magazines_path

app/views/email_magazines/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @email_magazine.title

= link_to 'Edit', edit_email_magazine_path(@email_magazine)
\|
= link_to 'Back', email_magazines_path