config/routes.rb
Rails.application.routes.draw do
  resources :email_magazines

  resources :recipes, only: [:new, :create, :edit, :show, :update] do
    get :search, on: :collection
    member do
      delete :delete_image
      patch :publish
    end

    resources :directions, only: [:create, :update, :destroy] do
      member do
        delete :delete_image
        patch :move_highter
        patch :move_lower
      end
    end

    resources :tukurepos, only: [:create]
  end

  resources :kitchens, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyCookpad
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default
      .navbar-header
        = link_to 'my-cookpad', root_path, class: 'navbar-brand'
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          = form_tag search_recipes_path, method: :get, class: "navbar-form navbar-left" do
            = text_field_tag :search, "", placeholder: "Search", class: "form-control"
            = submit_tag "検索"
          %li= link_to 'レシピをのせる', new_recipe_path if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to current_user.default_nickname + "'s Kitchen", kitchen_path(current_user.id)
            %li= link_to 'プロフィール変更', edit_user_registration_path
            %li= link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'ユーザー登録（無料）', new_user_registration_path
            %li= link_to 'ログイン', new_user_session_path

    - if notice
      .alert.alert-desmissable.alert-success
        %button.close(type="button" data-dismiss="alert") x
        %p.notice= notice
    - if alert
      .alert.alert-dismissable.alert-danger
        %button.close(type="button" data-dismiss="alert") x
        %p.alert= alert

    = yield

    #footer
      .container
        .row
          .col-md-8
            %p Copyleft my-cookpad(c) All Left Reserved

app/views/layouts/readable.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "my_cookpad"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "readable", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "readable"
    = yield(:page_javascript) if content_for?(:page_javascript)